#!/bin/sh

#####################################
#
# remove legacy python scripts
#
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_delete_last_marker.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_delete_last_marker.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_einspieler.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_einspieler.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_import_shownotes.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_import_shownotes.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_notes.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_notes.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit_past.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit_past.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_marker.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_marker.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_namedmarker.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_namedmarker.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_webserver.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_webserver.py
fi
#
#####################################

#####################################
#
# ultraschall_delete_last_marker.Lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_delete_last_marker.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_delete_last_marker.lua
fi

#####################################
#
# ultraschall_safemode_start_pause.lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_safemode_start_pause.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_safemode_start_pause.lua
fi

#####################################
#
# ultraschall_safemode_start_stop.lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_safemode_start_stop.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_safemode_start_stop.lua
fi

#####################################
#
# ultraschall_set_edit_past.lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit_past.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit_past.lua
fi

#####################################
#
# ultraschall_set_edit.lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit.lua
fi

#####################################
#
# ultraschall_set_namedmarker.lua
#
#####################################
if [ -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_namedmarker.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_namedmarker.lua
fi

# if [ -d ~/Library/Application\ Support/REAPER ]; then
#   TIMESTAMP=$(date +"%Y%m%d%H%M%S")
#   if [ ! -d ~/Library/Application\ Support/Ultraschall/Backups ]; then
#     mkdir -p ~/Library/Application\ Support/Ultraschall/Backups
#   fi
#   cp -pPR ~/Library/Application\ Support/REAPER ~/Library/Application\ Support/Ultraschall/Backups/REAPER-${TIMESTAMP}
# fi
