#!/bin/sh
if [ ! -d ~/Library/Application\ Support/REAPER/Scripts ]; then
  mkdir ~/Library/Application\ Support/REAPER/Scripts
fi

mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_einspieler.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_einspieler.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_import_shownotes.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_import_shownotes.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_notes.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_notes.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_set marker2.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set marker2.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_set_edit.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_edit.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_set_marker.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_marker.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_set_namedmarker.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_set_namedmarker.py
mv ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_webserver.py ~/Library/Application\ Support/REAPER/Scripts/ultraschall_webserver.py


