#!/bin/sh

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/libmp3lame.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/libmp3lame.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/libmp4v2.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/libmp4v2.dylib
fi
